version: '3.8'
services:
  stats-server:
    build: ewm-stats-service
    container_name: stats_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsBase
      - POSTGRES_USER=art
      - POSTGRES_PASSWORD=pknk

  stats-db:
    image: postgres:15.1-alpine
    container_name: stats_db_container
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statsBase
      - POSTGRES_USER=art
      - POSTGRES_PASSWORD=pknk

  ewm-service:
    build: ewm-main-service
    container_name: main_service_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/mainBase
      - POSTGRES_USER=art
      - POSTGRES_PASSWORD=pknk

  ewm-db:
    image: postgres:15.1-alpine
    container_name: ewm_db_container
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=mainBase
      - POSTGRES_USER=art
      - POSTGRES_PASSWORD=pknk