version: '3.1'

services:
  stats-server:
    build: ewm-stats-service/service
    container_name: stats_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - POSTGRES_USER=art
      - POSTGRES_PASSWORD=pknk

  stats-db:
    image: postgres:14-alpine
    container_name: stats_db_container
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=art
      - POSTGRES_PASSWORD=pknk

  ewm-service:
    build: ewm-main-service/
    container_name: main_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main
      - POSTGRES_USER=art
      - POSTGRES_PASSWORD=pknk

  ewm-db:
    image: postgres:14-alpine
    container_name: main_db_container
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=art
      - POSTGRES_PASSWORD=pknk